name: pingvite
description: "Event Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  get_it: ^8.2.0
  dartz: ^0.10.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
  geolocator: ^14.0.2
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  google_fonts: ^6.3.1
  form_field_validator: ^1.1.0
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  gap: ^3.0.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png/app_logo.png"
  adaptive_icon_background: "#f8fbff"
  adaptive_icon_foreground: "assets/png/app_icon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/jpg/


flutter_native_splash:
  color: "#f8fbff"            
  image: assets/png/splashscreen.png 
  android: true
  ios: true
  web: false

  android_12:
    image: assets/png/splashscreen.png
    icon_background_color: "#f8fbff"

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
